# Codemagic configuration for Flutter iOS app
workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - app_store_connect # 稍後需在 Codemagic 後台 Environment variables 綁定
      flutter: stable
    triggering:
      events:
        - push
    scripts:
      - name: Manual Code signing
        script: |
          keychain initialize
          keychain add-certificates --certificate ios_distribution.p12 --certificate-password "1234"
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp ios_distribution.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
      - name: Get packages
        script: |
          flutter packages pub get
      - name: Flutter build ipa
        script: |
          flutter build ipa --release --build-name=1.0.0 --build-number=1
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID


